dist: bionic
language: generic

addons:
  apt:
    packages:
      - git
      - wget
      - flex
      - bison
      - make
      - gperf
      - python3
      - python3-pip
      - python-setuptools
      - python-serial
      - python-click
      - python-cryptography
      - python-future
      - python-pyparsing
      - python-pyelftools
      - cmake
      - ninja-build
      - ccache
      - libffi-dev
      - libssl-dev
      - libncurses-dev
      - doxygen


before_install:
# - sudo apt-get -y install doxygen
# Save path to the git repository
- PROJECT_PATH=$(pwd)

install:
- pip3 install -U codespell
- pip3 install -U travis-sphinx
- pip3 install -U sphinx-rtd-theme
- pip3 install -U breathe
- pip3 install -U exhale
# Install ESP32 toochain following steps as described
# in https://docs.espressif.com/projects/esp-idf/en/latest/get-started/#get-started-get-prerequisites
- mkdir -p ~/esp
- cd ~/esp
- git clone --recursive https://github.com/espressif/esp-idf.git
- cd ~/esp/esp-idf
# - git checkout release/v4.0
- ./install.sh
- export IDF_PATH=~/esp/esp-idf
- export PATH=$PATH:$HOME/esp/esp-idf/tools
- . $HOME/esp/esp-idf/export.sh
- cd $PROJECT_PATH

jobs:
  include:
    # Code spell
    - name: "Code-spell" 
      script: ./dist/tools/codespell/check.sh
    # Build test
    - name: "Build-Test"
      script: idf.py build
    # Run unit-tests
    - name: "Unit-Test"
      script: idf.py --help
    # Build and deploy documentation
    - name: "Deploy documentation"
      script: 
          - "travis-sphinx build --nowarn --source doc/"
          - "travis-sphinx deploy --branches dev"

env:
  global:
    secure: houW6Q5bbUYqQwVRf5Osmp/PjEItXHZMNQBTjqAJDHMFVFZS6pRoj1nYuT+z9IOgV2U7wHlKQv1yCGbSC/7B0ckaGSNw2sgP1lBJGFDmQxfRZ6sWPqKLyKjLGLpDdf08QMXxeoBnFKMQEKDv9CquVkHxgYVYxKexTE0FbNFXkuiCIEVbW2wWczsJHuEmlwm9tSkHMmPdJjMGJhFcddO5sBS2YL2cKTi07L4JP2nCFicImihhGozDE0uz0lu5rA75YDqatKDpL6MoQa1Q8s2x5BPh/mHCjE6Vjo36Yc9GT8ZVgO4AdjXsgZeCH5GCa48Ap9xIkjvXsG/37YXTsllogJ+HaSyrjn8HASCPpUHgyRGf//CBXohCEQ4t1kDG/hJSodXZNZJbNkxQySOlOitSdR1kJiRFKs/tbawb50wmEkzo+gvkl+p4Dq3IyzOsv9aQ7ys5kmJ5/ySwvaAU5ZUz1sR9p8rNh2coYOua3lvkkrZhWDTM64B6XelxP2ndDAT5AEcwrHlw/nUNWUexNHziw51inXPr/q9wIdDnRtf9ltkLQpZZODZlCK1K/6cIQRZuERRJH0AXaqWfajdWpjZbA9/8JwdtkiKZF/gD97zI/q1J3WW+p/Q5l7F/rAq6lsBtOhckXgwdEBllzlV33UjkYyTjr+cEw2PehgYqMYZ6zXM=
