language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
before_install:
- sudo apt-get -y install doxygen
install:
- pip install -U travis-sphinx
- pip install -U sphinx-rtd-theme
- pip install -U breathe
- pip install -U exhale
- pip install -U platformio
- platformio update
script:
- platformio run
- travis-sphinx build --nowarn --source doc/
after_success:
- travis-sphinx deploy --branches dev
env:
  global:
    secure: sfpiICA2PdzEhK12QRNKjzji/Oey6wgi+JQaHicEk2whoRnyIzkPz6PWEWIoT5fxRQIPR6CoDFHB/IohDWrESc+aaylPuLSQEY3jh0we6yyFBdrsT/QGhxycSrI8Zap2+1IjQEQJwpabhqCdcTYanaLKrETzGIfOgfK1Fn9xQyUO9+Y2EOq+nrd8MBB0J1W8MVgWGrQFmnGHwd3RfjS7MfVxyMPFTd95tJfRMg/5bNmmdRAEha6rO/+2WDZhpwq+yIeFD9shnW8CpT2b3qv9V4oksb3S+d0cU5SVsNaj8a8k9Y2L/tl87XyBlFhyKPCuzrwOVrKnb0Mopgu5gU1u0RXF1hCGlishbzGPP+wUqdeORrhH7xRzIoBl0mxXW1Ly9KvdnH7k5tEsz0jHDe0/ZHgb3LnhqSo1Q701zXAqzTWK561tK9MwRIn3XEj0VwzcTWGr3++AySmLqIorTHu5+T4q0HhWRSwT0mLWn/sAH6rMW79FTJFAlvyU4ttK8Bpy2Yc7QxaxJooV5pzmR13UJFQwrPyrwLld5cU0XOjVFycOH3v9eIHz66U3Cv40Ld16yUasLAge3finWjxem3KY7Ns8lTbK1JeKeJLwi3U6+MQHNOw8bJL2x8efQQI25bSLIpyrT8F8IHbcPxLF13xrRvX++oO50DoiZpIbsuJpJPU=
