language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
before_install:
- sudo apt-get -y install doxygen
install:
- pip install -U travis-sphinx
- pip install -U sphinx-rtd-theme
- pip install -U breathe
- pip install -U exhale
- pip install -U platformio
- platformio update
script:
- platformio run
- travis-sphinx build --nowarn --source doc/
after_success:
- travis-sphinx deploy --branches dev
env:
  global:
    secure: ZGUASDfGPO1CirWMwSxDcY4vg/HylfaNmSyF9KlXrEcAEHDowy7uMCoipN0ARwplooLwlMhHAuQ0n2lSgpfyG7aCC/IaCfNwyfa5LvXEdUJQhbqu2rri320IVFvj9SestrofClcKmuJcbd46BhDyXWO3OyVhg+PbY44LRq/Qqr3QmwKWaoysvUc18HXIrTTdkg/Ra+NGRsYICjg06Wqbwm72ZxRnv0mdobwkWDJfWFe5NXFSOTuiawDgWzmtDLbXrJQ702tFqL0cQRtSssfuVpNnNFxWtXXIdEDAo+vL35B0niNGSJ7gSR0TywYyXKS2Dm5zZKQQOqsbW7yV+Pn1uky4QYZahYAsi14UGbI99WUEYeSp/o9o+EmDEsFCzi6dMRORHTWIeKsIRaKvt0yXKndfxP5Zho39IwXgudZuPpNMEyKQYUh5Af+hEAGeVymsO+Qrj1ywVQ4Ez/Eg3zzBo2ZwJGX546tiQbHKb7ZDLcaQE6zXW2AuHFBY9VVR1DvnzBU9GGEuGrjhzXWMERCztyFmJZG+jFOYWOJgSuou/Y5eQAnKqkEMhF+mViBUms1QfDZnnSpeHLYGC8LzwEuR8GgdwcrSpYpcIn/4w67634B7vNdsaMG7gNGqoMSGrTPKn/Mnjg29VbU/zNkfhYmW9BXYYbr6dgvg/5bYzK6t8qc=
